project_name: cluster-capacity
release:
  github:
    owner: holyhope
    name: cluster-capacity
builds:
  - id: cluster-capacity
    goos:
    - linux
    - windows
    - darwin
    goarch:
    - amd64
    - "386"
    env:
      - CGO_ENABLED=0
      - GO111MODULE=on
    main: cmd/plugin/main.go
    ldflags: -s -w
      -X github.com/holyhope/cluster-capacity/pkg/version.version=
archives:
  - id: cluster-capacity
    builds:
    - cluster-capacity
    name_template: "{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}"
    format_overrides:
    - goos: windows
      format: zip
