apiVersion: krew.googlecontainertools.github.com/v1alpha2
kind: Plugin
metadata:
  name: cluster-capacity
spec:
  version: "v0.1.0"
  platforms:
  - selector:
      matchLabels:
        os: linux
        arch: amd64
    uri: https://github.com/holyhope/cluster-capacity/releases/download/v0.1.0/cluster-capacity_linux_amd64.tar.gz
    sha256: ""
    files:
    - from: "./cluster-capacity"
      to: "."
    - from: LICENSE
      to: "."
    bin: "cluster-capacity"
  - selector:
      matchLabels:
        os: darwin
        arch: amd64
    uri: https://github.com/holyhope/cluster-capacity/releases/download/v0.1.0/cluster-capacity_darwin_amd64.tar.gz
    sha256: ""
    files:
    - from: "./cluster-capacity"
      to: "."
    - from: LICENSE
      to: "."
    bin: "cluster-capacity"
  - selector:
      matchLabels:
        os: windows
        arch: amd64
    uri: https://github.com/holyhope/cluster-capacity/releases/download/v0.1.0/cluster-capacity_windows_amd64.zip
    sha256: ""
    files:
    - from: "/cluster-capacity.exe"
      to: "."
    - from: LICENSE
      to: "."
    bin: "cluster-capacity.exe"
  shortDescription: A new plugin
  homepage: https://github.com/holyhope/cluster-capacity
  caveats: |
    Usage:
      $ kubectl cluster-capacity

    For additional options:
      $ kubectl cluster-capacity --help
      or https://github.com/holyhope/cluster-capacity/blob/v0.1.0/doc/USAGE.md

  description: |
    This is a new plugin
